CREATE TABLE IF NOT EXISTS translation_task (
    task_id              VARCHAR(36)  NOT NULL PRIMARY KEY,
    file_name            VARCHAR(255) NOT NULL,
    file_path            VARCHAR(500),
    original_backup_path VARCHAR(500),
    output_file_path     VARCHAR(500),
    status               VARCHAR(20)  NOT NULL DEFAULT 'waiting',
    translated_count     INT          DEFAULT 0,
    total_count          INT          DEFAULT 0,
    target_lang          VARCHAR(20)  DEFAULT 'zh-CN',
    error_message        TEXT,
    creation_version_id  BIGINT,
    sync_fail_count      INT          NOT NULL DEFAULT 0,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS custom_prompt (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    TEXT         NOT NULL,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dictionary_entry (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_text VARCHAR(500) NOT NULL,
    target_text VARCHAR(500) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_source_text UNIQUE (source_text)
);

CREATE TABLE IF NOT EXISTS creation (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255) NOT NULL,
    translated_name   VARCHAR(255),
    author            VARCHAR(255),
    cc_link           VARCHAR(1000),
    nexus_link        VARCHAR(1000),
    remark            TEXT,
    tags              VARCHAR(1000),
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS creation_version (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creation_id     BIGINT       NOT NULL,
    version         VARCHAR(50)  NOT NULL,
    file_path       VARCHAR(500),
    file_share_link VARCHAR(1000),
    patch_file_path VARCHAR(500),
    patch_file_name VARCHAR(255),
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS creation_image (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creation_id   BIGINT       NOT NULL,
    image_path    VARCHAR(500) NOT NULL,
    sort_order    INT          DEFAULT 0,
    deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
